name: Export ArchiMate Images
on: 
  push:
    branches:
      - main
    paths:
      - 'architecture/**.archimate'
      - 'architecture/rename_images.py'
  pull_request:
    branches:
      - main
    paths:
      - 'architecture/**.archimate'
      - 'architecture/rename_images.py'

jobs:
  archi_export:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Archi Report
        uses: docker://ghcr.io/woozymasta/archimate-ci-image:5.7.0-1.0.6
        with:
          args: >
            dbus-run-session -- xvfb-run -a /opt/Archi/Archi 
            -nosplash -consoleLog -application com.archimatetool.commandline.app
            --loadModel /github/workspace/architecture/entrust_architecture.archimate 
            --html.createReport /github/workspace/architecture/.report

      - name: Rename Images
        id: rename_images
        run: |
          pip install beautifulsoup4
          model=`ls -d architecture/.report/id-* | head -n 1`
          echo "Model directory: $model"
          ls $model/images/*
          sudo chown -R $USER:$USER architecture/.report/
          ls -ld $model/images
          python architecture/rename_images.py $model
          echo "images_dir=$model/images" >> $GITHUB_OUTPUT

      - name: Extract Images and Commit
        run: |
          git config --global --add safe.directory /github/workspace

          echo "Listing generated image files:"
          ls -R ${{ steps.rename_images.outputs.images_dir }}
          
          mkdir -p docs/images          
          cp -r ${{ steps.rename_images.outputs.images_dir }}/* docs/images/
          
          rm -rf architecture/.report
          
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/images/
          git commit -m "Automated image export" || exit 0
          git push
