name: Export ArchiMate Images
on: 
  push:
    branches:
      - main

jobs:
  archi_export:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

#      - name: Prepare Image Directory
#        run: |
#          mkdir -p architecture/.images
#          ls -lRa architecture

      - name: Generate Archi Report
        uses: docker://ghcr.io/woozymasta/archimate-ci-image:5.7.0-1.0.6
        with:
          args: >
            dbus-run-session -- xvfb-run -a /opt/Archi/Archi 
            -nosplash -consoleLog -application com.archimatetool.commandline.app
            --loadModel /github/workspace/architecture/entrust_architecture.archimate 
            --html.createReport /github/workspace/architecture/.report
#            --script.run /github/workspace/architecture/export_views.ajs

      - name: Rename Images
        run: |
          pip install beautifulsoup4
          model=`ls -d architecture/.report/id-* | head -n 1`
          echo "Model directory: $model"
          python architecture/rename_images.py architecture/.report/$model

      - name: Extract Images and Commit
        run: |
          # Fix the Git ownership error
          git config --global --add safe.directory /github/workspace

          echo "Listing generated report files:"
          ls -R architecture/.report
          
          # Prepare image folder
          mkdir -p docs/images
          
          # Copy images from the generated report
          cp -r architecture/.images/* docs/images/
          
          # Cleanup report (optional, keeps repo clean)
          rm -rf architecture/.report
          
          # Commit
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/images/
          git commit -m "Automated image export" || exit 0
          git push
